### ISSUE TITLE
An issue about Procedural Model in plugin for RPG Maker MZ

### ISSUE THREAD

**Issue by NemesisC** [effekseer/EffekseerForRPGMakerMZ_Ex#6]
Dear Effekseer Programmer,

I am an Effekseer and RPG Maker MZ user and your software gives me a lot of favor on my work. I really love working with it. However, I have a small question about it. May I ask if your Effekseer plugin for RPG Maker MZ includes ProceduralModel inside? Those samples with ProceduralModel could not be shown in Animation of RPG Maker MZ but those without it work with MZ. Could you please have a check on it?

I hope to receive your response if you would like to. Have a nice day.

Kind regards,
Chester

**Comment by durswd** [comment]
Did you overwrite libs?

**Comment by NemesisC** [comment]
Thank you for your prompt reply. At first, I did not overwrite those two in libs. I just downloaded them and overwrote the originals but it still did not work. There is no animation shown. I did replace all textures inside it from my project folder.

**Comment by NemesisC** [comment]
Thank you for your reply. I replied to you from github.

**Comment by NemesisC** [comment]
I meant I tried with latest files in libs just now but it still did not work. I used the file "Aura01.efkefc" in "00_Version16" folder of the samples.

**Comment by durswd** [comment]
![image](https://user-images.githubusercontent.com/5775729/132544319-810bb1f3-c442-42c3-8f25-f4da41f6483b.png)

A procedural model can be shown in RPG Maker MZ.

It is another problem.

**Comment by NemesisC** [comment]
I really thank you a lot for sparing your time on helping me solve my issue. I rebuilt a new file by using some parameters from yours and now it works. I am going to find out the reason for this issue myself. Have a nice weekend.
